/******************************************************************************
* This file is AUTO-GENERATED by CodeGenerator.
* DONNOT modify it by hands UNLESS you know what you are doing.
*
* To aquire for source codes of the Generator or for any help,
* please mail to [ahda86@gmail.com].
*
* Bug Reports & Improvement Suggestions are Appreciated.
******************************************************************************/


#ifndef __MHZ_MSG_HANDLER_H_MHZ__
#define __MHZ_MSG_HANDLER_H_MHZ__

#include "framework/websocket/websocketmessagehandler.h"
#include "Core/EventHandler.h"

namespace cg
{
    class CMassageHandler
        : public virtual cdf::CWsMessageHandler
    {
    public:
        virtual void onMessage(const cdf::CWSContextPtr & context,
            const std::string & data,
            websocketpp::frame::opcode::value operCode);

        inline void setEventHandler(const CEventHandlerPtr & eventHandler)
        {
            _eventHandler = eventHandler;
        }
    private:
        CEventHandlerPtr _eventHandler;
    };
    typedef cdf::CHandle<CMassageHandler> CMassageHandlerPtr;

} //close namespace cg;

#endif //__MHZ_MSG_HANDLER_H_MHZ__
